[Variables]
@include = #@#style.inc
SkinWidth = (#rightSize# * #scale#)
SkinHeight = (#areaH# * 0.16)
FontColor = 200,200,200
Settings = #CURRENTPATH#Settings.inc
ToggleKey =F5
InputSize = 22
space1 = (#SkinWidth# * 0.07) 
space2 = (#SkinWidth# * 0.21)

[styleTime]
Y = (#SkinHeight# * 0.01)
FontColor = #FontColor#
FontSize = (45 * #scale#)
StringAlign = Right

[styleColon]
Y=(#SkinHeight# * -0.13)
FontSize = (55 * #scale#)
Text = ":"
FontFace = 
StringAlign = Right
