;Games List
[Variables]
Total=20

name0 = 

name1=Ark
img1=czafx5m7.bmp
dir1=C:\Users\Andy Banks\Desktop\ARK Survival Ascended.url

name2=NFS Carbon
img2=nfs-carbon-logo.png
dir2=C:\Users\Andy Banks\Desktop\Need for Speed - Carbon.lnk	

name3=Cyberpunk 2077
img3=cyberpunk_2077_icon_by_s7_by_sidyseven_d60opl7-fullview.png
dir3=C:\Users\Andy Banks\Desktop\Cyberpunk 2077.url

name4=WoW
img4=256x256.png
dir4=C:\Users\Public\Desktop\World of Warcraft.lnk		

name5=ARK Dev Kit
img5=egs-arkdevkit-studiowildcard-ic1-400x400-1cb356e0b780.avif
dir5=C:\Users\Andy Banks\Desktop\ARK DevKit.url	

name6=
img6=empty
dir6=			

name7=
img7=empty
dir7=			

name8=
img8=empty
dir8=		

name9=
img9=empty
dir9=

name10=
img10=empty
dir10=	

name11=
img11=empty
dir11=	

name12=
img12=empty
dir12=																				

name13=
img13=empty
dir13=	

name14=
img14=empty
dir14=																						

name15=
img15=empty
dir15=	

name16=
img16=empty
dir16=	

name17=
img17=empty	
dir17=	

name18=
img18=empty
dir18=	

name19=
img19=empty
dir19=	

name20=
img20=empty
dir20=
