[Variables]
Total=20

name0 = 

name1=Slack
img1=elhna9ll.bmp
dir1=C:\Users\Andy Banks\Desktop\Slack.lnk

name2=Maya
img2=h84ylqt1.bmp
dir2=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Autodesk Maya LT 2020\Maya LT 2020.lnk	

name3=Paint
img3=lb5v9oun.bmp
dir3=C:\Desktop\Programs\Paint.lnk

name4=Cura
img4=twqevjua.bmp
dir4=C:\Desktop\Programs\Ultimaker Cura 4.13.0.lnk			

name5=Dilan
img5=image (1).png
dir5=http://game-u.com/accvirtual			

name6=Notepad++
img6=Notepad_plus_plus.png
dir6=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Notepad++.lnk			

name7=GitHub
img7=image.png
dir7=C:\Users\Andy Banks\Desktop\GitHub Desktop.lnk			

name8=iCUE
img8=1o4fzh55.bmp
dir8=C:\ProgramData\Microsoft\Windows\Start Menu\Corsair\iCUE\iCUE.lnk			

name9=LD Player
img9=Untitled.jpg
dir9=C:\Users\Andy Banks\Desktop\Dark Money\LDPlayer9.lnk

name10=Memu
img10=507a6965f32d702499488a7392af9a4b.png
dir10=C:\Users\Andy Banks\Desktop\Dark Money\MEmu.lnk	

name11=Google Remote Desktop
img11=image (3).png
dir11=https://remotedesktop.google.com/support/?pli=1	

name12=
img12=empty
dir12=

name13=
img13=empty
dir13=	

name14=
img14=empty
dir14=

name15=
img15=empty
dir15=	

name16=TEST
img16=empty
dir16=	

name17=
img17=empty
dir17=	

name18=
img18=empty
dir18=	

name19=
img19=empty
dir19=	

name20=
img20=empty
dir20=																						
