[Variables]
Total=20

name0 = 

name1=Slack
img1=elhna9ll.bmp
dir1=C:\Desktop\Programs\Slack.lnk

name2=Maya
img2=h84ylqt1.bmp
dir2=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Autodesk Maya LT 2020\Maya LT 2020.lnk	

name3=Paint
img3=lb5v9oun.bmp
dir3=C:\Desktop\Programs\Paint.lnk

name4=Cura
img4=twqevjua.bmp
dir4=C:\Desktop\Programs\Ultimaker Cura 4.13.0.lnk			

name5=Dilan
img5=image (1).png
dir5=http://game-u.com/accfriday			

name6=Notepad++
img6=Notepad_plus_plus.png
dir6=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Notepad++.lnk			

name7=
img7=
dir7=			

name8=
img8=
dir8=			

name9=
img9=
dir9=

name10=
img10=
dir10=	

name11=
img11=
dir11=	

name12=
img12=	
dir12=																				

name13=
img13=	
dir13=	

name14=
img14=	
dir14=																						

name15=
img15=	
dir15=	

name16=
img16=	
dir16=	

name17=
img17=	
dir17=	

name18=
img18=	
dir18=	

name19=
img19=
dir19=	

name20=
img20=
dir20=																						
