[Variables]
Total=20

name0 = 

name1=Ark
img1=czafx5m7.bmp
dir1=C:\Users\Andy Banks\Desktop\ARK Survival Evolved.url

name2=Red Alert 2
img2=v15mjyem.bmp
dir2=C:\Users\Andy Banks\Desktop\Command & Conquer Red Alert™ 2 and Yuri’s Revenge™.url	

name3=Cyberpunk 2077
img3=cyberpunk_2077_icon_by_s7_by_sidyseven_d60opl7-fullview.png
dir3=C:\Users\Andy Banks\Desktop\Cyberpunk 2077.url

name4=WoW
img4=256x256.png
dir4=C:\Users\Public\Desktop\World of Warcraft.lnk			

name5=Raid
img5=empty
dir5=C:\Users\Andy Banks\Desktop\Raid Shadow Legends.lnk			

name6=
img6=empty
dir6=			

name7=
img7=empty
dir7=			

name8=
img8=empty
dir8=		

name9=
img9=empty
dir9=

name10=
img10=empty
dir10=	

name11=
img11=empty
dir11=	

name12=
img12=empty
dir12=																				

name13=
img13=empty
dir13=	

name14=
img14=empty
dir14=																						

name15=
img15=empty
dir15=	

name16=
img16=empty
dir16=	

name17=
img17=empty	
dir17=	

name18=
img18=empty
dir18=	

name19=
img19=empty
dir19=	

name20=
img20=empty
dir20=
