[Variables]
Total=20

name0 = 

name1=Ark
img1=czafx5m7.bmp
dir1=C:\Desktop\Games\ARK Survival Evolved.url

name2=WWH
img2=z8vx81t6.bmp
dir2=C:\Desktop\Games\World War Heroes.lnk	

name3=Mech Arena
img3=8tr4vi7j.bmp
dir3=C:\Users\Andy Banks\Desktop\Mech Arena.lnk

name4=
img4=
dir4=			

name5=
img5=
dir5=			

name6=
img6=
dir6=			

name7=
img7=
dir7=			

name8=
img8=
dir8=		

name9=
img9=
dir9=

name10=
img10=
dir10=	

name11=
img11=
dir11=	

name12=
img12=	
dir12=																				

name13=
img13=	
dir13=	

name14=
img14=	
dir14=																						

name15=
img15=	
dir15=	

name16=
img16=	
dir16=	

name17=
img17=	
dir17=	

name18=
img18=	
dir18=	

name19=
img19=
dir19=	

name20=
img20=
dir20=																						

dgdfgdfgdf=
gdfgdfgdfg=
