[Variables]
Total=20

name0 = 

name1=Ark
img1=czafx5m7.bmp
dir1=C:\Users\Andy Banks\Desktop\ARK Survival Evolved.url

name2=WWH
img2=v15mjyem.bmp
dir2=C:\Users\Andy Banks\Desktop\World War Heroes.lnk	

name3=Cyberpunk 2077
img3=cyberpunk_2077_icon_by_s7_by_sidyseven_d60opl7-fullview.png
dir3=C:\Users\Andy Banks\Desktop\Cyberpunk 2077.url

name4=WoW
img4=256x256.png
dir4=C:\Users\Public\Desktop\World of Warcraft.lnk			

name5=
img5=
dir5=			

name6=
img6=
dir6=			

name7=
img7=
dir7=			

name8=
img8=
dir8=		

name9=
img9=
dir9=

name10=
img10=
dir10=	

name11=
img11=
dir11=	

name12=
img12=	
dir12=																				

name13=
img13=	
dir13=	

name14=
img14=	
dir14=																						

name15=
img15=	
dir15=	

name16=
img16=	
dir16=	

name17=
img17=	
dir17=	

name18=
img18=	
dir18=	

name19=
img19=
dir19=	

name20=
img20=
dir20=
