[Metadata]
Name=Dark Claws
Author=Andy
Information=
Version=

[Rainmeter]
Update=1000
SkinWidth = #SkinWidth#
SkinHeight = #SkinHeight#
ContextTitle = Settings.inc
ContextAction = ["#Settings#"]
ContextTitle2 = Open HWiNFO64
ContextAction2 = ["#hwInfo#"]

[Variables]
@Include1 = #@#style.inc
@Include2 = Settings.inc
drives = 2
fontSize = 30
row1Y = 0
offset = (#SkinHeight# * 0.37)
row2Y = (#SkinHeight# * 0.5)

[skinStyle]
FontSize = #fontSize#
StringAlign= Right
Y = r

[ScrollButton]
MouseScrollUpAction =  [!WriteKeyValue Variables driveNum 1 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages1.ini"]
MouseScrollDownAction=[!WriteKeyValue Variables driveNum 3 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages3.ini"]

;=============================================
;	DRIVE 1
;=============================================
[MeterDrive1]
Meter=String
MeterStyle = styleText | skinStyle
X = (#SkinWidth# * 0.)
Y = #row1Y#
StringAlign = Left
Text = #disk1#
Hidden = ([MeasureUsed1] = 0)

[MeterDrive1Temp]
MeasureName = MeasureTemp1
Meter=String
MeterStyle = styleText | skinStyle
X = (#SkinWidth# * 0.12)
StringAlign = Left
Hidden = ([MeasureUsed1] = 0)

[MeterDrive1Percent]
MeasureName = MeasurePercentUsed1
Meter=String
MeterStyle = styleText  | skinStyle
X = (#SkinWidth# * 0.415)
Text = %1%
StringAlign = Left

[MeterDrive1Used]
MeasureName = MeasureUsed1
Meter=String
MeterStyle = styleText | skinStyle | storage
X = (#SkinWidth# * 0.9)
NumOfDecimals = 0
StringAlign = Right
Hidden = ([MeasureUsed1] = 0)
FontSize = 18

[MeterDrive1Total]
MeasureName = MeasureTotal1
Meter=String
MeterStyle = styleText  | skinStyle | storage
X = r
Y = (#SkinHeight# * 0.25)
StringAlign = Right
Hidden = ([MeasureUsed1] = 0)
FontSize = 18

[MeterLine1]
Meter=Shape
Shape = Rectangle 0,0, (#SkinWidth# * 0.2), 1| Extend Look
X = (#SkinWidth# * -0.22)r
Y = (#row1Y# + #SkinHeight# * 0.225)
Look = Fill Color #bgColor# | StrokeWidth #stroke# | Stroke Color #olColor#

[MeterBarUsed1]
MeasureName = MeasurePercentUsed1
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.009)
Y = (#row1Y# + #SkinHeight# * 0.37)
W = (#SkinWidth# * 0.6)
H = (#SkinHeight# * 0.10)
DynamicVariables = 1

;=============================================
;	DRIVE 2
;=============================================
[MeterDrive2]
Meter=String
MeterStyle = styleText | skinStyle
X = (#SkinWidth# * 0.)
Y = #row2Y#
StringAlign = Left
Text = #disk2#
Hidden = ([MeasureUse2 = 0)

[MeterDrive2Temp]
MeasureName = MeasureTemp2
Meter=String
MeterStyle = styleText | skinStyle
X = (#SkinWidth# * 0.12)
StringAlign = Left
Hidden = ([MeasureUsed2] = 0)

[MeterDrive2Percent]
MeasureName = MeasurePercentUsed2
Meter=String
MeterStyle = styleText  | skinStyle
X = (#SkinWidth# * 0.415)
Text = %1%
StringAlign = Left

[MeterDrive2Used]
MeasureName = MeasureUsed2
Meter=String
MeterStyle = styleText | skinStyle | storage
X = (#SkinWidth# * 0.9)
NumOfDecimals = 0
StringAlign = Right
Hidden = ([MeasureUsed2] = 0)
FontSize = 18

[MeterDrive2Total]
MeasureName = MeasureTotal2
Meter=String
MeterStyle = styleText  | skinStyle | storage
X = r
Y = (#SkinHeight# * 0.25)r
StringAlign = Right
Hidden = ([MeasureUsed2] = 0)
FontSize = 18

[MeterLine2]
Meter=Shape
Shape = Rectangle 0,0, (#SkinWidth# * 0.2), 1| Extend Look
X = (#SkinWidth# * -0.22)r
Y = (#row2Y# + #SkinHeight# * 0.225)
Look = Fill Color #bgColor# | StrokeWidth #stroke# | Stroke Color #olColor#

[MeterBarUsed2]
MeasureName = MeasurePercentUsed2
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.009)
Y = (#row2Y# + #SkinHeight# * 0.37)
W = (#SkinWidth# * 0.6)
H = (#SkinHeight# * 0.10)
DynamicVariables = 1

[MeterSettings]
Meter = Image
MeterStyle = Settings

