[Metadata]
Name=Dark Claws
Author=Andy
Information=
Version=

[Rainmeter]
Update=1000
SkinWidth = #SkinWidth#
SkinHeight = #SkinHeight#
ContextTitle = Settings.inc
ContextAction = ["#Settings#"]
ContextTitle2 = Open HWiNFO64
ContextAction2 = ["#hwInfo#"]

[Variables]
@Include1 = #@#style.inc
@Include2 = Settings.inc
drives = 1
fontSize = 30

[skinStyle]
Y = r
FontSize = #fontSize#

[ScrollButton]
MouseScrollUpAction =  [!WriteKeyValue Variables driveNum 4 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages4.ini"]
MouseScrollDownAction=[!WriteKeyValue Variables driveNum 2 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages2.ini"]

;=============================================

[MeterDrive1]
Meter=String
MeterStyle = styleText | drive1 | skinStyle
X = (#SkinWidth# * 0.0)
Y = 0
Text = #disk1#
StrignAlign = Left

[MeterDrive1Percent]
MeasureName = MeasurePercentUsed1
Meter=String
MeterStyle = styleText  | drive1 | skinStyle
X = (#SkinWidth# * 0.15)
Text = %1%

[MeterDrive1Total]
MeasureName = MeasureTotal1
Meter=String
MeterStyle = styleText  | drive1 | skinStyle | storage
X = (#SkinWidth# * 0.95)
StringAlign = Right

[MeterBarUsed1]
MeasureName = MeasurePercentUsed1
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.005)
Y = (#SkinHeight# * 0.43)
H = (#SkinHeight# * 0.20)
AutoScale = 1
NumOfDecimals = 0
DynamicVariables = 1

[MeterDrive1Temp]
MeasureName = MeasureTemp1
Meter=String
MeterStyle = styleText | drive1 | skinStyle
X = (#SkinWidth# * 0.15)
Y = (#SkinHeight# * 0.65)
Hidden = ([MeasureUsed1] = 0)

[MeterDrive1Used]
MeasureName = MeasureUsed1
Meter=String
MeterStyle = styleText | drive1 | skinStyle | storage
X = (#SkinWidth# * 0.95)
StringAlign = Right

[MeterSettings]
Meter = Image
MeterStyle = Settings


