[Metadata]
Name=Dark Claws
Author=Andy
Information=
Version=

[Rainmeter]
Update=1000
SkinWidth = #SkinWidth#
SkinHeight = #SkinHeight#
ContextTitle = Settings.inc
ContextAction = ["#Settings#"]
ContextTitle2 = Open HWiNFO64
ContextAction2 = ["#hwInfo#"]


[Variables]
@Include1 = #@#style.inc
@Include2 = Settings.inc
drives = 4
fontSize = 17
Row1 = (#SkinHeight# * 0.0)
;RowOffset is the space between each row:
RowOffset = (#SkinHeight# * 0.25)

[skinStyle]
Y = r
FontSize = #fontSize#

[ScrollButton]
MouseScrollUpAction =  [!WriteKeyValue Variables driveNum 3 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages3.ini"]
MouseScrollDownAction=[!WriteKeyValue Variables driveNum 1 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages1.ini"]

[driveName]
X = (#SkinWidth# * 0.0)
Y = (#RowOffset# - #BarY#)r
StringAlign= left
FontSize = #fontSize#

[driveTemp]
X = (#SkinWidth# * 0.1)

[drivePercent]
X =(#SkinWidth# * 0.27)
Text = %1%

[driveUsed]
X = (#SkinWidth# * 0.9)
AutoScale = 1
NumOfDecimals = 0
Text= %1B / %2B
StringAlign= right

;=============================================

[MeterDrive1]
Meter=String
MeterStyle = styleText | skinStyle | drive1 | driveName
Y = #Row1#
Text = #disk1#

[MeterDrive1Temp]
MeasureName = MeasureTemp1
Meter=String
MeterStyle = styleText | skinStyle | drive1 | driveTemp

[MeterDrive1Percent]
MeasureName = MeasurePercentUsed1
Meter=String
MeterStyle = styleText  | skinStyle | drive1 | drivePercent

[MeterDrive1Used]
MeasureName = MeasureUsed1
MeasureName2 = MeasureTotal1
Meter=String
MeterStyle = styleText | skinStyle | drive1 | driveUsed

[MeterBarUsed1]
MeasureName = MeasurePercentUsed1
Meter = Bar
MeterStyle = drive1 | driveBar

;=============================================
[MeterDrive2]
Meter=String
MeterStyle = styleText | skinStyle | drive2 | driveName
Text = #disk2#

[MeterDrive2Temp]
MeasureName = MeasureTemp2
Meter=String
MeterStyle = styleText | skinStyle | drive2 | driveTemp
Hidden = ([MeasureUsed2] = 0)

[MeterDrive2Percent]
MeasureName = MeasurePercentUsed2
Meter=String
MeterStyle = styleText  | skinStyle | drive2 | drivePercent

[MeterDrive2Used]
MeasureName = MeasureUsed2
MeasureName2 = MeasureTotal2
Meter=String
MeterStyle = styleText | skinStyle | drive2 | driveUsed

[MeterBarUsed2]
MeasureName = MeasurePercentUsed2
Meter = Bar
MeterStyle = drive2 | driveBar
Hidden = ([MeasureUsed2] = 0)

;=============================================
[MeterDrive3]
Meter=String
MeterStyle = styleText | skinStyle | drive3 | driveName
Text = #disk3#

[MeterDrive3Temp]
MeasureName = MeasureTemp3
Meter=String
MeterStyle = styleText | skinStyle | drive3 | driveTemp

[MeterDrive3Percent]
MeasureName = MeasurePercentUsed3
Meter=String
MeterStyle = styleText  | skinStyle | drive3 | drivePercent

[MeterDrive3Used]
MeasureName = MeasureUsed3
MeasureName2 = MeasureTotal3
Meter=String
MeterStyle = styleText | skinStyle | drive3 | driveUsed

[MeterBarUsed3]
MeasureName = MeasurePercentUsed3
Meter = Bar
MeterStyle = drive3| skinStyle | driveBar

;=============================================
[MeterDrive4]
Meter=String
MeterStyle = styleText | skinStyle | drive4 | driveName
Text = #disk4#

[MeterDrive4Temp]
MeasureName = MeasureTemp4
Meter=String
MeterStyle = styleText | skinStyle | drive4 | driveTemp

[MeterDrive4Percent]
MeasureName = MeasurePercentUsed4
Meter=String
MeterStyle = styleText  | skinStyle | drive4 | drivePercent

[MeterUsed4]
MeasureName = MeasureUsed4
MeasureName2 = MeasureTotal4
Meter=String
MeterStyle = styleText | skinStyle | drive4 | driveUsed

[MeterBar4]
MeasureName = MeasurePercentUsed4
Meter = Bar
MeterStyle = drive4 | skinStyle | driveBar

[MeterSettings]
Meter = Image
MeterStyle = Settings
