[Metadata]
Name=Dark Claws
Author=Andy
Information=
Version=

[Rainmeter]
Update=1000
SkinWidth = #SkinWidth#
SkinHeight = #SkinHeight#
ContextTitle = Settings.inc
ContextAction = ["#Settings#"]
ContextTitle2 = Open HWiNFO64
ContextAction2 = ["C:\ProgramData\Microsoft\Windows\Start Menu\Programs\HWiNFO64\HWiNFO64"]

[Variables]
@Include1 = #@#style.inc
@Include2 = Settings.inc

[MeterBG]
Meter = Shape
MeterStyle = styleBG

[driveName]
X = (#SkinWidth# * 0.0)
Y = (#RowOffset# - #BarY#)r
StringAlign= left
FontSize = #FontSize#

[driveTemp]
X = #TempX#
Y = r
FontSize = #FontSize#

[driveUsed]
X = #UsedX#
Y = r
AutoScale = 1
NumOfDecimals = 2
Text= %1B / %2B
StringAlign= right
FontSize = #FontSize#

[driveBar]
X = #BarX#
Y = #BarY#r
W = #BarW#
H = #BarH# 
BarColor = #hlColor#
SolidColor = #bgColor#
BarOrientation = Horizontal


;=============================================

[MeterDrive1]
Meter=String
MeterStyle = styleText | driveName
X = (#SkinWidth# * 0.1)
Y = (#SkinHeight * 0.4)
Text = #disk1#
FontSize = 30
Hidden = ([MeasureUsed1] = 0)

[MeterDriveTemp1]
MeasureName = MeasureTemp1
Meter=String
MeterStyle = styleText | driveTemp
X = (#SkinWidth# * 0.02)
Y = (#SkinHeight# * 0.5)
FontSize = 30
Hidden = ([MeasureUsed1] = 0)

[MeterDriveUsed1]
MeasureName = MeasureUsed1
MeasureName2 = MeasureTotal1
Meter=String
MeterStyle = styleText | driveUsed
X = (#SkinWidth# * 0.0)
Y = (#SkinHeight * 0.0)
FontSize = 15
Hidden = ([MeasureUsed1] = 0)

[MeterBarUsed1]
MeasureName = MeasurePercentUsed1
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.0)
Y = (#SkinHeight * 0.0)
Hidden = ([MeasureUsed1] = 0)


[MeterSettings]
Meter = Image
MeterStyle = Settings
X = (#CURRENTCONFIGWIDTH# * 0.94)
Y = (#CURRENTCONFIGHEIGHT# * 0.05)