[Metadata]
Name=Dark Claws
Author=Andy
Information=
Version=

[Rainmeter]
Update=1000
SkinWidth = #SkinWidth#
SkinHeight = #SkinHeight#
ContextTitle = Settings.inc
ContextAction = ["#Settings#"]
ContextTitle2 = Open HWiNFO64
ContextAction2 = ["#hwInfo#"]


[Variables]
@Include1 = #@#style.inc
@Include2 = Settings.inc
drives = 3
fontSize = 18
startX = (#SkinWidth# * 0.15)
offset = (#SkinWidth# * 0.31)

[skinStyle]
FontSize = #fontSize#
StringAlign= Center
X = r
Y = (#SkinHeight# * 0.2)r

[ScrollButton]
MouseScrollUpAction =  [!WriteKeyValue Variables driveNum 2 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages2.ini"]
MouseScrollDownAction=[!WriteKeyValue Variables driveNum 4 Settings.inc][!ActivateConfig "#CURRENTCONFIG#" "DC_Storages4.ini"]

;=============================================
;	DRIVE 1
;=============================================
[MeterDrive1]
Meter=String
MeterStyle = styleText | skinStyle
X = #startX#
Y = 0
Text = #disk1#
Hidden = ([MeasureUsed1] = 0)

[MeterDrive1Temp]
MeasureName = MeasureTemp1
Meter=String
MeterStyle = styleText | skinStyle
Hidden = ([MeasureUsed1] = 0)

[MeterDrive1Percent]
MeasureName = MeasurePercentUsed1
Meter=String
MeterStyle = styleText  | skinStyle
Text = %1 %

[MeterDrive1Used]
MeasureName = MeasureUsed1
Meter=String
MeterStyle = styleText | skinStyle | storage
NumOfDecimals = 0
Hidden = ([MeasureUsed1] = 0)

[MeterDrive1Total]
MeasureName = MeasureTotal1
Meter=String
MeterStyle = styleText  | skinStyle | storage
Hidden = ([MeasureUsed1] = 0)

[MeterBarUsed1]
MeasureName = MeasurePercentUsed1
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.12)r
Y = (#SkinHeight# * 0.1)
W = (#SkinWidth# * 0.03)
H = (#SkinHeight# * 0.9)
BarOrientation = Vertical

;=============================================
;	DRIVE 2
;=============================================
[MeterDrive2]
Meter=String
MeterStyle = styleText | skinStyle
X = (#startX# + #offset#)
Y = 0
Text = #disk2#
Hidden = ([MeasureUsed2] = 0)

[MeterDrive2Temp]
MeasureName = MeasureTemp2
Meter=String
MeterStyle = styleText | skinStyle
Hidden = ([MeasureUsed2] = 0)

[MeterDrive2Percent]
MeasureName = MeasurePercentUsed2
Meter=String
MeterStyle = styleText  | skinStyle
Text = %1 %

[MeterDrive2Used]
MeasureName = MeasureUsed2
Meter=String
MeterStyle = styleText | skinStyle | storage
NumOfDecimals = 0
Hidden = ([MeasureUsed2] = 0)

[MeterDrive2Total]
MeasureName = MeasureTotal2
Meter=String
MeterStyle = styleText  | skinStyle | storage
Hidden = ([MeasureUsed2] = 0)

[MeterBarUsed2]
MeasureName = MeasurePercentUsed2
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.12)r
Y = (#SkinHeight# * 0.1)
W = (#SkinWidth# * 0.03)
H = (#SkinHeight# * 0.9)
BarOrientation = Vertical

;=============================================
;	DRIVE 3
;=============================================
[MeterDrive3]
Meter=String
MeterStyle = styleText | skinStyle
X = (#startX# + #offset# * 2)
Y = 0
Text = #disk3#
Hidden = ([MeasureUsed3] = 0)

[MeterDrive3Temp]
MeasureName = MeasureTemp3
Meter=String
MeterStyle = styleText | skinStyle
Hidden = ([MeasureUsed3] = 0)

[MeterDrive3Percent]
MeasureName = MeasurePercentUsed3
Meter=String
MeterStyle = styleText  | skinStyle
Text = %1 %

[MeterDrive3Used]
MeasureName = MeasureUsed3
Meter=String
MeterStyle = styleText | skinStyle | storage
NumOfDecimals = 0
Hidden = ([MeasureUsed3] = 0)

[MeterDrive3Total]
MeasureName = MeasureTotal3
Meter=String
MeterStyle = styleText  | skinStyle | storage
Hidden = ([MeasureUsed3] = 0)

[MeterBarUsed3]
MeasureName = MeasurePercentUsed3
Meter = Bar
MeterStyle = driveBar
X = (#SkinWidth# * 0.12)r
Y = (#SkinHeight# * 0.1)
W = (#SkinWidth# * 0.03)
H = (#SkinHeight# * 0.9)
BarOrientation = Vertical


[MeterSettings]
Meter = Image
MeterStyle = Settings

