[Metadata]
Name=Dark Claws
Author=Andy

[Rainmeter]
Update=60
SkinWidth = #SkinWidth#
SkinHeight = #SkinHeight#
ContextTitle = Settings.inc
ContextAction = ["#Settings#"]
ContextTitle2 = Code
ContextAction2 = ["#CURRENTPATH#Code.lua"]

[Variables]
@Include1 = #@#style.inc
@Include2 = SettingsPIC.inc
@Include3 = #@#GalleryView.inc
Settings = #CURRENTPATH#SettingsPIC.inc

[MeterGIF]
Meter=String
MeterStyle = styleText | textHighlight
Y = (#SkinHeight# * 0.85)
Text= IMAGE
LeftMouseUpAction= [!ActivateConfig #CURRENTCONFIG# "DC_GIF.ini"]

[MeterPicName]
Meter=String
MeterStyle = styleText
X = (#SkinWidth# * 0.5)
Y = (#SkinHeight# * 0.85)
StringAlign = Center
Text = "No Folder"
DynamicVariables = 1

[MeterFolderName]
Meter=String
MeterStyle = styleText
MeasureName = MeasureFolderName
X = (#SkinWidth# * 0.5)
Y = (#SkinHeight# * 0.9)
StringAlign = Center

[MeterShuffle]
Meter = Image
ImageName = #@#shuffle.png
X = (#SkinWidth# * 0.58)
Y = (#SkinHeight# * 0.95)
W = (#SkinWidth# * 0.055)
PreserveAspectRatio = 1
DynamicVariables = 1
LeftMouseDownAction = [!SetOption #CURRENTSECTION# ImageTint #clColor#]
LeftMouseUpAction = [!CommandMeasure "MainLua" "ChangeShuffle()"]

[MeterTimerLabel]
Meter=String
MeterStyle = styleText | textHighlight
X = (#SkinWidth# * 0.0)
Y = (#SkinHeight# * 0.95)
Fontsize = 17
Text= Minutes
DynamicVariables=1
LeftMouseUpAction = [!CommandMeasure "MainLua" "ChangeTimeMode()"]

;=================================================
; 	TIMER
;=================================================
[MeterTimerBox]
Meter=Shape
;DO NOT CHANGE THE FIRST TWO ZEROES
Shape = Rectangle 0,0, (#SkinWidth# * 0.1), (#SkinHeight# * 0.05) | Extend Look
X = (#SkinWidth# * 0.16)
Y = (#SkinHeight# * 0.945)
Look = Fill Color #bgColor# | StrokeWidth #stroke# | Stroke Color #olColor#
MouseScrollUpAction = [!CommandMeasure "MainLua" "ChangeTime(1)"]
MouseScrollDownAction = [!CommandMeasure "MainLua" "ChangeTime(-1)"]

[MeterTimerNumber]
Meter=String
MeterStyle = styleText
X = (#SkinWidth# * 0.21)
Y = (#SkinHeight# * 0.95)
Fontsize = 17
Text= #seconds#
StringAlign = Center

