[Variables]
@Include1 = #@#style.inc
Editor = "EditorPIC.ini"
Settings = "SettingsPIC.inc"
MyConfig = "DC_Picture.ini"
index =16
current =17
;If 1, we're using minutes, If 0, we're using seconds, 2 if we're at super speed
timeMode =0
seconds =10
paused =1
shuffle =0
current=3
SkinWidth = (#scale# * #midSize#)
SkinHeight = (#areaH# *  1)

path =C:\Users\Andy Banks\Desktop\Andy\Kormos
folder =1
folder1 = "C:\Users\Andy Banks\Desktop\Andy\Kormos"
folder2 =C:\Users\Andy Banks\Pictures\Acuhorn
folder3 =C:\Users\Andy Banks\Pictures\Acuhorn
folder4 =...
folder5 = "C:\Users\Andy Banks\Desktop\Test"
folder6 =C:\Users\Andy Banks\Pictures\Screenshots
folder7 = ...
folder8 =...
folder9 = ...
folder10 = ...


