[Variables]
@Include1 = #@#style.inc
SkinWidth = (#rightSize# * #scale#)
SkinHeight = (#areaH# * 0.208)
Settings = #CURRENTPATH#Settings.inc
InputSize = (16 * #scale#)
BarScale = 0
Box1X = 0
Box1Y = 0
Box2X =(#SkinWidth# * 0.5)
Box2Y = 0
Box3X = 0
Box3Y =  (#SkinHeight# * 0.5)
Box4X =  (#SkinWidth# * 0.5)
Box4Y =  (#SKinHeight# * 0.5)

;User input variables
tempLow =30
tempHigh =70
clrLow =0,0,180
clrMed =0,0,255
clrHgh =0,255,255
